spring.application.name: bootStudy

server.port: 80

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource: 
    url: jdbc:log4jdbc:mariadb://localhost:3306/test
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: 0118
    hikari:
      minimum-idle: 1
      maximum-pool-size: 1
      connection-init-sql: select now()
mybatis:
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true


